spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: toor
    username: postgres
    url: jdbc:postgresql://localhost:5432/
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  server:
    error:
      include-message: always
